name: Resourcepack Zipper

on:
  push:
    branches:
      - main  # Adjust this branch name if needed
      
permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Run PackSquash
      uses: ComunidadAylas/PackSquash-action@v4
      with:
        packsquash_version: latest
        options: |
            pack_directory = '.'
            output_file_path = '/tmp/RP.zip'
            allow_mods = ['OptiFine']
            
    - name: Tag and create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: action-v${{ github.run_number }}
        files: /tmp/RP.zip
